'use client';
import { useEffect,useState } from 'react';
import { ArrowLeft, UserPlus, Trash2, Ban, CheckCircle2 } from 'lucide-react';
type U={id:number,email:string,role:string,display_name:string,enabled:number,created_at:string,last_login_at:string|null};
export default function Admin(){const [users,setUsers]=useState<U[]>([]);const [me,setMe]=useState<any>(null);const [form,setForm]=useState({email:'',password:'',displayName:'',role:'user'});const [msg,setMsg]=useState('');
 async function load(){const m=await fetch('/api/me').then(r=>r.json());setMe(m.user);if(m.user?.role==='admin')setUsers((await fetch('/api/admin/users').then(r=>r.json())).users||[])} useEffect(()=>{load()},[]);
 if(me===null)return <main className="center"><div className="loader"/></main>; if(me?.role!=='admin')return <main className="center"><div className="panel"><h2>Admin only</h2><a href="/">← Back to lab</a></div></main>;
 async function create(e:React.FormEvent){e.preventDefault();const r=await fetch('/api/admin/users',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(form)});const j=await r.json();setMsg(r.ok?'User created':j.error||'Error');if(r.ok){setForm({email:'',password:'',displayName:'',role:'user'});load()}}
 async function toggle(id:number){await fetch(`/api/admin/users/${id}/toggle`,{method:'POST'});load()} async function del(id:number){if(confirm('Delete this user and all their data?')){await fetch(`/api/admin/users/${id}`,{method:'DELETE'});load()}}
 return <main className="shell"><header className="topbar"><a href="/" className="back"><ArrowLeft size={18}/> Lab</a><b>User management</b><span/></header><section className="admin-grid"><div className="panel"><div className="panel-title"><div><h2>Create user</h2><p className="muted">Regular users keep their own saved profiles and experiments.</p></div><UserPlus/></div><form onSubmit={create} className="stack"><input placeholder="Display name" value={form.displayName} onChange={e=>setForm({...form,displayName:e.target.value})}/><input placeholder="Email" type="email" value={form.email} onChange={e=>setForm({...form,email:e.target.value})}/><input placeholder="Password" type="password" value={form.password} onChange={e=>setForm({...form,password:e.target.value})}/><select value={form.role} onChange={e=>setForm({...form,role:e.target.value})}><option value="user">User</option><option value="guest">Guest</option></select><button className="primary">Create account</button>{msg&&<small className="muted">{msg}</small>}</form></div><div className="panel"><div className="panel-title"><div><h2>Accounts</h2><p className="muted">Guest data is automatically disposable.</p></div></div><div className="user-list">{users.map(u=><div className="user-row" key={u.id}><div><b>{u.display_name}</b><small>{u.email} · {u.role}</small></div><span className={u.enabled?'status on':'status'}>{u.enabled?'active':'disabled'}</span><button className="icon-btn" onClick={()=>toggle(u.id)} title="Enable/disable">{u.enabled?<Ban size={17}/>:<CheckCircle2 size={17}/>}</button>{u.role!=='admin'&&<button className="icon-btn danger" onClick={()=>del(u.id)} title="Delete"><Trash2 size={17}/></button>}</div>)}</div></div></section></main>}
